#ifndef WETMAN_UTILS_NET_ERROR_CODE_H
#define WETMAN_UTILS_NET_ERROR_CODE_H


typedef enum
{
    RETURN_CODE_OK,
    RETURN_CODE_INVALID_ENDPOINT_ID,
    RETURN_CODE_ENDPOINT_NOT_INITIALIZED,
    RETURN_CODE_FAILED_TO_PARSE_REQUEST,
    RETURN_CODE_INTERNAL_ENDPOINT_ERROR,

    RETURN_CODE_CUSTOM,
} ReturnCode;

#endif // WETMAN_UTILS_NET_ERROR_CODE_H
