#ifndef WETMAN_SHARED_PERSISTENCE_STATUS_H
#define WETMAN_SHARED_PERSISTENCE_STATUS_H


typedef enum {
    PERSISTENCE_STATUS_OK,
    PERSISTENCE_STATUS_FILE_DOES_NOT_EXIST,
    PERSISTENCE_STATUS_WRONG_FORMAT,
} PersistenceStatus;

#endif // WETMAN_SHARED_PERSISTENCE_STATUS_H
