#ifndef TEST_SHARED_ENDPOINT_ID_H
#define TEST_SHARED_ENDPOINT_ID_H

#define TEST_ENDPOINT_ID_ECHO_I32 0
#define TEST_ENDPOINT_ID_ECHO_STR 1
#define TEST_ENDPOINT_ID_ECHO_FD 2

#endif // TEST_SHARED_ENDPOINT_ID_H
